# Generated by Django 3.1.1 on 2020-09-17 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0002_auto_20200917_0641'),
    ]

    operations = [
        migrations.DeleteModel(
            name='upload',
        ),
    ]
